### ISSUE TITLE
[SW SQL Server Products] - Report Error

### ISSUE THREAD

**Issue by alexchurch22** [MEM-Zone/sccm-zone.com#11]
I'm using the latest HINV Classes and Configuration.mof properties and have let them sit in our environment for four days or so (with daily hardware inventories). I'm also using the latest copy of the SQL report. I'm getting an error when trying to generate a report.

An error has occurred during report processing. (rsProcessingAborted)
Query execution failed for dataset 'SQLProductInfo'. (rsErrorExecutingCommand)
Error converting data type nvarchar to bit. | An error has occurred during report processing. (rsProcessingAborted)

**Comment by Ioan-Popovici** [comment]
Probably a wrong assumption that the BIT declared variables can only have values of 0 or 1. Will look into it tomorrow (actually today it’s past midnight), I may ask you to run a query some query to confirm.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ioan-Popovici** [comment]
Seems that another user has found the issue here: https://github.com/SCCM-Zone/sccm-zone.github.io/issues/5

Some parameters are missing in the older SQL versions. I will push an update tomorrow.

Thank you for reporting this

**Comment by Ioan-Popovici** [comment]
I managed to test the query on a much bigger dataset than my current lab could offer, found the problem and also a few other bugs. (It will be in the changelog)

I used the larger dataset to validate some of the results and it seems that as far as I can tell the query returns accurate data. The mof optimization to gather only sql service data (ServiceType = 1) works better than expected, discarding a lot of junk that does not need to be filtered in the report now.

Since the extension also detects sql express and WID instances, I will add the option to filter out multiple versions in the report.

Will push an update for the query and report as soon as possible. (Most likely tomorrow)


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ioan-Popovici** [comment]
# [Released v2.5 SW SQL Server Products](https://github.com/SCCM-Zone/sccm-zone.github.io/commit/10fb5e15bef5ed54386b2272bd4d73683df82be5#diff-2bf3e497db780df4efc6d9f4fb09f3ad)

## Changelist

* Added edition group filter with multiple selections
* Added CEIP Reporting (Customer Experience Improvement)
* Removed unused fields
* Fixed SKUName
* Updated formatting

Please let me know if this fixes the issue for you so I can close the issue

**Comment by alexchurch22** [comment]
I'm unable to import the updated .RDL file. I get the error below. My SQL reporting services site is running on SQL 2016.


An error has occurred. 


 The definition of this report is not valid or supported by this version of Reporting Services. The report definition may have been created with a later version of Reporting Services, or contain content that is not well-formed or not valid based on Reporting Services schemas. Details: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

**Comment by Ioan-Popovici** [comment]
Yeah, I’m using SSRS 2017. Just edit the file with a text editor and replace the definition header with a header from one of your reports. It will tell you then which elements are not supported and you can remove them one by one. Be sure to remove the open and close tags for those elements. I don’t have a 2016 SSRS available at the moment to get you a compatible report file, but I’ll try to build you one with visual studio.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexchurch22** [comment]
The 2017 file seems to be formatted differently. The 2016 one I exported from my SSRS site is in XML format at the one you've uploaded looks to be HTML. I don't see a way to convert it.

**Comment by Ioan-Popovici** [comment]
I just looked at the report definitions and they haven't changed. You are probably downloading the file wrong. Always right click the raw version if you want to download the file.
Here is the link https://github.com/SCCM-Zone/sccm-zone.github.io/raw/master/Reporting/Software/SW%20SQL%20Server%20Products/SW%20SQL%20Server%20Products.rdl

**Comment by alexchurch22** [comment]
Yup, that was it. Got it to import and run now. Looks good. It looks like on my end that SQL 2016 is being grouped to together, but the value under the "Release" column is blank. I also have one of SQL 2014 being classified as "SQL Unknown". What details can I provide?

**Comment by Ioan-Popovici** [comment]
A screenshoot would be nice.
I get the release from the CUVersion so if that is visible I can see where things go boom.
However it should not be possible for the release to be blank...

**Comment by alexchurch22** [comment]
Here's the one with the blank column that I believe is SQL 2016:

![Screenshot1](https://user-images.githubusercontent.com/50494538/61395854-09835300-a88c-11e9-819b-1224df1daf73.png)

Here's the "SQL Unknown" one.

![Screenshot2](https://user-images.githubusercontent.com/50494538/61395889-19029c00-a88c-11e9-9919-f2c87c99543d.png)

**Comment by Ioan-Popovici** [comment]
# [Released 2.6.3](https://github.com/SCCM-Zone/sccm-zone.github.io/tree/master/Reporting/Software/SW%20SQL%20Server%20Products)

## Blank release bug
I've updated the release definitions from here: https://sqlserverbuilds.blogspot.com/

## 'SQL Unknown' (SQL 2014)
The file version is missing and I'm also using the first four characters (2014) to match the license key to the SQL instance so I don't know exactly what to do about that.
The file version should be 2014.120.6024.0.

I could use the version for matching but that would complicate things a lot.
If it's just one machine you could either add the file version manually in WMI or just live with it...

**Comment by wespowell** [comment]
Thanks for posting an update to the SQL. I saw the issue yesterday and updated my rdl file manually. I am having a small issue and its really not a big deal but the Clustered value is always coming back as 0. If I manually run the query against wmi and the SqlServiceAdvancedProperty it does return a 1 which should indicate a Yes. But what is in the database is a 0. I ran the query with and without single quotes around the 1 and the value was returned properly.
![2019-07-17_14-33-56](https://user-images.githubusercontent.com/12397970/61407636-d220a080-a8a3-11e9-9ac2-c4937d8cbe3f.png)
![2019-07-17_14-39-41](https://user-images.githubusercontent.com/12397970/61407640-d51b9100-a8a3-11e9-93f6-c1b26df4c1fc.png)

**Comment by Ioan-Popovici** [comment]
Hi @wespowell,

Your assumption that the SQLServiceType value stands for Clustered is incorrect as you can see below:

# [SqlServiceType Property (SqlServiceAdvancedProperty Class)](https://docs.microsoft.com/en-us/sql/relational-databases/wmi-provider-configuration-classes/sqlserviceadvancedproperty-class/sqlservicetype-property-sqlserviceadvancedproperty-class?view=sql-server-2017)
## Property Value/Return Value
A uint32 value that specifies the SQL Server Service type.

Type | Definition
-- | --
1 | MSSQLSERVER is the SQL Server service.
2 | SQLSERVERAGENT is the SQL Server Agent service.
3 | MSFTESQL is the SQL Server Full-text Search Engine service.
4 | MsDtsServer is the Integration Services service.
5 | MSSQLServerOLAPService is the Analysis Services service.
6 | ReportServer is the Reporting Services service.
7 | SQLBrowser is the SQL Server Browser service.
8 | NsService is the Notification Services Notification service.
9 | MSSQLFDLauncher is the SQL Server Full-text Filter Daemon Launcher service.
10 | SQLPBENGINE is the SQL Server Polybase Engine service.
11 | SQLPBDMS is the SQL Server Polybase Data Movement service.
12 | MSSQLLaunchpad is the SQL Server Launchpad service.

I'm actually filtering everything out that is not SQLServiceType, in order to reduce noise and database footprint.

I don't have a cluster to check if the CLUSTERED value actually changes in WMI.
If you know any other place in WMI where I can look for the Clustered value please let me know and I will include it in the extension.

Thank you,
Ioan

**Comment by Ioan-Popovici** [comment]
I'm going to close this issue since the original problem was fixed.
Feel free to open another issue if you find a bug or need assistance.
Please open a separate issue for each request type :D

Thank you all for your contribution
Ioan

**Comment by wespowell** [comment]
Thanks for the quick response. I will see about sending you some info from wmi.

**Comment by Ioan-Popovici** [comment]
You can use [WMI Explorer](https://github.com/vinaypamnani/wmie2/releases/tag/v2.0.0.2)
It's arguably one of the best tools for the job.
I could be also a registry value but that would require another class which I would want to avoid if possible.
