### ISSUE TITLE
Conversion failed when converting value to data type

### ISSUE THREAD

**Issue by Ioan-Popovici** [MEM-Zone/sccm-zone.com#4]
@Yevrag35

Running the report gives me:
![conversionfailed](https://user-images.githubusercontent.com/20248838/53521508-4bab2400-3aa6-11e9-98fd-ff69e80d7f49.png)
How do I begin debugging this?

**Comment by Ioan-Popovici** [comment]
I have a lot of reports, which one are you refering to?

**Comment by Yevrag35** [comment]
Oh sorry, it's the "CB Configuration Baseline Compliance by Configuration Item with Values" one.

However, a colleague and I found the issue, we believe.  The ID's in the error correspond with 'AdminIDs' for Administrative users in SCCM.  And the issue only happens to users who are members of multiple groups and/or specified explicitly in the administrative users section in the console.

In my case, my user account was explicitly defined as an admin AND I am a member of another group which is also defined as an admin in the console.  The error is actually coming from the definition of 'UserSIDs'.

My user's UserTokenSIDs as it passes into 'dbo.fn_rbac_GetAdminIDsfromUserSIDs' results in two ID's coming back from the function.  But instead of Microsoft listing them as 2 separate values, they concatenate them into one string joined with a comma.

Workaround:
Remove the duplicate Administrative User entry.

Fix?:
My colleague wrote some simple T-SQL to automatically split the string (if it needs to), and select the first ID in the newly created array.  This is, more than likely, not ideal as it's not checking for the highest permissions levels.

**Comment by Ioan-Popovici** [comment]
Hmm, I will look for a workaround, thanks for reporting this

**Comment by Yevrag35** [comment]
No problem, when I get into work, I will post the extra code that got it working.

**Comment by Ioan-Popovici** [comment]
For now the simple workaround is to uncomment this line
`--DECLARE @UserSIDs     AS NVARCHAR(250) = 1;`
If it does not work you might need to replace the value with 'Disabled'

NOTE: This will disable the report security!

**Comment by Ioan-Popovici** [comment]
Implemented workaround, upgraded report template and other optimisations.
Released v4.0
